[project]
name = "qr-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
    { name = "Andrija Junzki", email = "andrew.junzki@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "qrcode>=8.2",
]

[project.scripts]
qr-gen = "qr_gen:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyinstaller>=6.22.3",
    "pytest>=8.0",
]
